/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.Random;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void readJsonFileTest() {
        Gson gson = new Gson();
        try (Reader reader = new FileReader("recentquotes.json"))
        {
            RecentQuotes[]quotes=gson.fromJson(reader,RecentQuotes[].class);
            Random number = new Random();
          assertEquals("{\n" +
                  "    \"tags\": [\n" +
                  "      \"attributed-no-source\"\n" +
                  "    ],\n" +
                  "    \"author\": \"Marilyn Monroe\",\n" +
                  "    \"likes\": \"18651 likes\",\n" +
                  "    \"text\": \" “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.” \"\n" +
                  "  }",quotes[0]);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
