/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.util.Random;

public class App {
    public static void main(String[] args) {
        try{

            Gson gson=new Gson();
            URL url =new URL("https://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");
            connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");

            if(connection.getResponseCode()==200){

                InputStream inputStream = connection.getInputStream();
                InputStreamReader inputStreamReader = new InputStreamReader(inputStream);
                BufferedReader in = new BufferedReader(inputStreamReader);
               QuotesApi quotesApi=gson.fromJson(in,QuotesApi.class);
                System.out.println("Api quotes:" + quotesApi);
                in.close();

               try {
                   BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("ApiQuotes.json"));
                   String newQuotes = gson.toJson(quotesApi);
                   bufferedWriter.write(newQuotes);
                   bufferedWriter.close();

               }catch (Exception e){
                   System.out.println("something wrong");
               }

            }



        }catch (Exception e){

            Gson gson = new Gson();
            try (Reader reader = new FileReader("recentquotes.json"))
            {
                RecentQuotes[]quotes=gson.fromJson(reader,RecentQuotes[].class);
                Random number = new Random();
                int index=number.nextInt(quotes.length);
                System.out.println(quotes[index]);
            } catch (FileNotFoundException e2) {
                e2.printStackTrace();
            } catch (IOException e3) {
                e3.printStackTrace();
            }

        }


    }
}

