/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.Random;

public class App {
    public static void main(String[] args) {
        Gson gson = new Gson();
        try (Reader reader = new FileReader("recentquotes.json"))
        {
          RecentQuotes[]quotes=gson.fromJson(reader,RecentQuotes[].class);
            Random number = new Random();
            int index=number.nextInt(quotes.length);
            System.out.println(quotes[index]);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
